### ISSUE TITLE
Error in OAuth Server: Failed to complete OAuth handshake with vkontakte. self signed certificate in certificate chain

### ISSUE THREAD

**Issue by dvjeshka** [alexpods/meteor-accounts-vk#19]
(packages\logging.js:113) Error in OAuth Server: Failed to complete OAuth handshake with vkontakte. self signed certificate in certificate chain
I20180429-15:07:01.325(3)? Exception while invoking method 'login' Error: Failed to complete OAuth handshake with vkontakte. self signed certificate in certificate chain
I20180429-15:07:01.341(3)?     at getTokenResponse (packages\thundefined_accounts-vk.js:122:24)
I20180429-15:07:01.341(3)?     at Object.handleOauthRequest (packages\thundefined_accounts-vk.js:71:23)
I20180429-15:07:01.347(3)?     at OAuth._requestHandlers.(anonymous function) (packages\oauth2.js:27:31)
I20180429-15:07:01.348(3)?     at middleware (packages\oauth.js:203:5)
I20180429-15:07:01.349(3)?     at packages\oauth.js:176:5

**Comment by dvjeshka** [comment]
this solution has helped, but it is not the best
https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request
